import * as T from 'three';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
import { floorHeight, regionSeed, seededRandom, oceanMaterial, swayMaterial } from './materials.js';

const SIZE=128,RADIUS=2;
export class StreamingOcean {
  constructor(world){
    this.world=world;this.scene=world.scene;this.chunks=new Map();this.pool=[];this.pending=[];this.cell='';this.quality='high';this.center=new T.Vector2();this.bounds={value:new T.Vector4(-256,384,-256,384)};
    this.terrainMaterial=oceanMaterial('#ffffff',{vertexColors:true});
    this.shared={rock:world.rockG,coral:world.branchGeometry(),grass:world.grass.geometry};
    const star=new T.Shape();for(let i=0;i<10;i++){const a=i*Math.PI/5,r=i%2?.16:.5;const x=Math.cos(a)*r,y=Math.sin(a)*r;if(i===0)star.moveTo(x,y);else star.lineTo(x,y);}star.closePath();const starG=new T.ExtrudeGeometry(star,{depth:.07,bevelEnabled:true,bevelSize:.03,bevelThickness:.025,bevelSegments:1,steps:1});starG.rotateX(-Math.PI/2);this.shared.star=starG;
    const shell=new T.SphereGeometry(1,16,8,0,Math.PI,0,Math.PI);shell.scale(.42,.16,.55);this.shared.shell=shell;
    const fanParts=[];for(let i=0;i<11;i++){const a=(i/10-.5)*2.4,tip=new T.Vector3(Math.sin(a)*1.2,Math.cos(a)*1.4+.4,0);fanParts.push(new T.TubeGeometry(new T.CatmullRomCurve3([new T.Vector3(),new T.Vector3(tip.x*.35,.6,.04),tip]),8,.027,4,false));for(let j=0;j<2;j++){const origin=tip.clone().multiplyScalar(.55+j*.2),end=origin.clone().add(new T.Vector3((i%2?1:-1)*.3,.28,.03));fanParts.push(new T.TubeGeometry(new T.LineCurve3(origin,end),1,.017,4,false));}}this.shared.fan=mergeGeometries(fanParts);fanParts.forEach(g=>g.dispose());
    const parts=[];for(let i=0;i<13;i++){const g=new T.CylinderGeometry(.018,.045,.65,4,4);g.translate(Math.sin(i*2.4)*.2,.3,Math.cos(i*2.4)*.2);parts.push(g);}this.shared.anemone=mergeGeometries(parts);parts.forEach(g=>g.dispose());
    const kelpParts=[];for(let i=0;i<9;i++){const leaf=new T.SphereGeometry(1,6,4);leaf.scale(.45,.10,1.4);leaf.rotateZ(i*.6);leaf.translate(Math.sin(i)*.35,.6+i*.65,Math.cos(i)*.3);kelpParts.push(leaf);}this.shared.kelp=mergeGeometries(kelpParts);kelpParts.forEach(g=>g.dispose());
    this.shared.sponge=new T.CylinderGeometry(.32,.55,1.5,10,1,true);
    this.materials={kelp:swayMaterial('#737c3e',.055),sponge:oceanMaterial('#b99768'),rock:world.rockMat,coral:swayMaterial('#c079a7',.015),grass:swayMaterial('#659775',.12),star:oceanMaterial('#dc8e4e'),shell:oceanMaterial('#b1becb',{metalness:.18,roughness:.45}),fan:swayMaterial('#b85177',.04),anemone:swayMaterial('#7ed2b5',.12,{emissive:'#164a57',emissiveIntensity:.35})};
    const g=new T.PlaneGeometry(3072,3072,128,128);g.rotateX(-Math.PI/2);this.far=new T.Mesh(g,this.terrainMaterial.clone());this.far.material.onBeforeCompile=s=>{this.terrainMaterial.onBeforeCompile(s);s.uniforms.nearBounds=this.bounds;s.fragmentShader='uniform vec4 nearBounds;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('void main() {','void main() {\n if(vOceanWorld.x>nearBounds.x&&vOceanWorld.x<nearBounds.y&&vOceanWorld.z>nearBounds.z&&vOceanWorld.z<nearBounds.w)discard;');};this.far.material.customProgramCacheKey=()=> 'far-terrain';this.scene.add(this.far);
    this.update(new T.Vector3(0,9,26),true);
  }
  terrainGeometry(){const g=new T.PlaneGeometry(SIZE,SIZE,32,32);g.rotateX(-Math.PI/2);return g;}
  paintTerrain(mesh,cx,cz){const p=mesh.geometry.attributes.position,colors=mesh.geometry.attributes.color?.array||new Float32Array(p.count*3),c=new T.Color();for(let i=0;i<p.count;i++){const x=p.getX(i)+cx,z=p.getZ(i)+cz,y=floorHeight(x,z);p.setY(i,y);if(y>31)c.setHSL(.27,.26,.24+Math.sin(x*.1)*.025);else if(y>24)c.set('#d8c89b');else c.setHSL(.12+Math.min(.18,Math.max(0,-y)*.003),.18,.43+Math.sin(x*.2+z*.13)*.04);c.toArray(colors,i*3);}if(!mesh.geometry.attributes.color)mesh.geometry.setAttribute('color',new T.BufferAttribute(colors,3));mesh.geometry.attributes.color.needsUpdate=true;p.needsUpdate=true;mesh.geometry.computeVertexNormals();mesh.geometry.computeBoundingSphere();mesh.position.set(cx,0,cz);}
  createChunk(){const root=new T.Group(),terrain=new T.Mesh(this.terrainGeometry(),this.terrainMaterial);root.add(terrain);const meshes={};for(const [kind,count] of Object.entries({rock:15,coral:26,grass:50,star:9,shell:9,fan:12,anemone:12,kelp:18,sponge:12})){meshes[kind]=new T.InstancedMesh(this.shared[kind],this.materials[kind],count);root.add(meshes[kind]);}return {root,terrain,meshes,obstacles:[]};}
  fill(chunk,x,z){const random=seededRandom(regionSeed(x,z)),d=new T.Object3D();chunk.x=x;chunk.z=z;chunk.obstacles=[];const biome=regionSeed(x,z)%6;const cx=(x+.5)*SIZE,cz=(z+.5)*SIZE;this.paintTerrain(chunk.terrain,cx,cz);
    for(const [kind,mesh] of Object.entries(chunk.meshes)){let placed=0;for(let i=0;i<mesh.instanceMatrix.count;i++){const px=x*SIZE+random()*SIZE,pz=z*SIZE+random()*SIZE,py=floorHeight(px,pz);const inCore=px>-65&&px<75&&pz>-165&&pz<42;if((py>23&&kind!=='rock')||inCore)continue;const density=kind==='kelp'?(biome===4?.95:.06):kind==='sponge'?(biome===5?.95:.12):kind==='coral'?[1,.35,.15,.55,.1,.3][biome]:kind==='anemone'?[.45,1,.2,.4,.2,.3][biome]:kind==='fan'?[.4,.35,.2,1,.1,.3][biome]:1;if(random()>density)continue;const scale=kind==='rock'?1.5+random()*4:kind==='coral'?.45+random()*1.5:.6+random();d.position.set(px,py+(kind==='rock'?.2:.07),pz);d.rotation.set(0,random()*Math.PI*2,0);d.scale.setScalar(scale);if(kind==='rock'){d.scale.y*=.6;chunk.obstacles.push({p:d.position.clone(),r:scale*.8});}d.updateMatrix();mesh.setMatrixAt(placed++,d.matrix);if(kind==='coral')mesh.setColorAt(placed-1,new T.Color().setHSL(.02+random()*.8,.4,.56));}mesh.count=placed;mesh.userData.fullCount=placed;mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;mesh.computeBoundingSphere();}
    chunk.root.visible=true;this.scene.add(chunk.root);
  }
  rebuildObstacles(){this.world.obstacles.length=this.world.baseObstacleCount;for(const chunk of this.chunks.values())this.world.obstacles.push(...chunk.obstacles);}
  update(player,immediate=false){
    const x=Math.floor(player.x/SIZE),z=Math.floor(player.z/SIZE),key=`${x},${z}`;
    if(key!==this.cell){this.cell=key;this.center.set(x,z);const wanted=new Set();this.pending=[];for(let dx=-RADIUS;dx<=RADIUS;dx++)for(let dz=-RADIUS;dz<=RADIUS;dz++){const k=`${x+dx},${z+dz}`;wanted.add(k);if(!this.chunks.has(k))this.pending.push({x:x+dx,z:z+dz,k,d:dx*dx+dz*dz});}for(const [k,c] of this.chunks)if(!wanted.has(k)){this.scene.remove(c.root);this.pool.push(c);this.chunks.delete(k);}this.pending.sort((a,b)=>a.d-b.d);this.bounds.value.set((x-RADIUS)*SIZE,(x+RADIUS+1)*SIZE,(z-RADIUS)*SIZE,(z+RADIUS+1)*SIZE);this.paintTerrain(this.far,(x+.5)*SIZE,(z+.5)*SIZE);this.rebuildObstacles();}
    const budget=immediate?25:1;for(let i=0;i<budget&&this.pending.length;i++){const job=this.pending.shift(),chunk=this.pool.pop()||this.createChunk();this.fill(chunk,job.x,job.z);this.chunks.set(job.k,chunk);this.rebuildObstacles();}
    for(const c of this.chunks.values()){const distance=Math.hypot((c.x+.5)*SIZE-player.x,(c.z+.5)*SIZE-player.z);for(const [kind,m] of Object.entries(c.meshes)){m.visible=distance<(this.quality==='low'?150:235);m.count=Math.floor(m.userData.fullCount*(this.quality==='low'&&kind!=='rock'?.5:1));}}
  }
  biomeAt(x,z){if(floorHeight(x,z)>20)return 'Island Shore';const seed=regionSeed(Math.floor(x/SIZE),Math.floor(z/SIZE));return ['Coral Highlands','Anemone Meadows','Sapphire Basin','Sea Fan Gardens','Ribbon Kelp Forest','Sponge Terraces'][seed%6];}
  dispose(){for(const c of [...this.chunks.values(),...this.pool]){this.scene.remove(c.root);c.terrain.geometry.dispose();Object.values(c.meshes).forEach(m=>m.dispose());}this.chunks.clear();this.pool=[];this.far.geometry.dispose();this.far.material.dispose();this.terrainMaterial.dispose();for(const [key,g] of Object.entries(this.shared))if(key!=='rock'&&key!=='grass')g.dispose();for(const [key,m] of Object.entries(this.materials))if(key!=='rock')m.dispose();}
}


